apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
  name: {{ .Values.operator.name }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: metricsservice
    port: 9666
    targetPort: 9666
  {{- if .Values.elasticsearch.operator.enabled }}
  - name: metrics
    port: {{ .Values.elasticsearch.operator.port }}
    targetPort: {{ .Values.elasticsearch.operator.port }}
  {{- end }}
  selector:
    app: {{ .Values.operator.name }}
