{{- if and .Values.elasticsearch.operator.enabled .Values.elasticsearch.operator.elasticsearchRules.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: elasticsearchRule
metadata:
  name: {{ .Values.operator.name }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
    {{- range $key, $value := .Values.elasticsearch.operator.elasticsearchRules.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.elasticsearch.operator.elasticsearchRules.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  groups:
  - name: {{ .Values.operator.name }}
    rules:
{{ toYaml .Values.elasticsearch.operator.elasticsearchRules.alerts | indent 6 }}
{{- end }}
