{{- if and .Values.elasticsearch.operator.enabled .Values.elasticsearch.operator.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Values.operator.name }}
  annotations:
    {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}
    {{- include "keda.labels" . | indent 4 }}
    {{- range $key, $value := .Values.elasticsearch.operator.podMonitor.additionalLabels }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- with .Values.elasticsearch.operator.podMonitor.namespace }}
  namespace: {{ . }}
  {{- end }}
spec:
  podMetricsEndpoints:
  - port: http
    path: /metrics
    honorLabels: true
    {{- with .Values.elasticsearch.operator.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.elasticsearch.operator.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.elasticsearch.operator.podMonitor.relabelings }}
    relabelings:
{{ toYaml . | indent 4 }}
    {{- end }}
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: {{ .Values.operator.name }}
{{- end }}
