apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: {{ .Values.operator.name }}-metrics-apiserver
    {{- include "keda.labels" . | indent 4 }}
  name: {{ .Values.operator.name }}-metrics-apiserver
  namespace: {{ .Release.Namespace }}
  annotations:
  {{- toYaml .Values.additionalAnnotations | nindent 4 }}
  {{- range $key, $value := .Values.service.annotations }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.portHttps }}
    targetPort: {{ .Values.service.portHttpsTarget }}
    protocol: TCP
  - name: http
    port: {{ .Values.service.portHttp }}
    targetPort: {{ .Values.service.portHttpTarget }}
    protocol: TCP
  {{- if .Values.elasticsearch.metricServer.enabled }}
  - name: {{ .Values.elasticsearch.metricServer.portName }}
    port: {{ .Values.elasticsearch.metricServer.port }}
    targetPort: {{ .Values.elasticsearch.metricServer.port }}
    protocol: TCP
  {{- end }}
  selector:
    app: {{ .Values.operator.name }}-metrics-apiserver
