{{ if has "elasticsearch" .Values.pump.backend }}
{{ if .Values.pump.elasticsearchPump.elasticsearchOperator.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: tyk-pump-podmonitor-{{ include "tyk-pump.fullname" . }}
  labels:
    {{- range $key, $value := .Values.pump.elasticsearchPump.elasticsearchOperator.podMonitorSelector }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: pump-{{ include "tyk-pump.fullname" . }}
  podMetricsEndpoints:
    - port: tyk-pump-port
{{ end }}
{{ end }}