{{- if .Values.maxUnavailable }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: "{{ template "myelasticsearch.uname" . }}-pdb"
  namespace: {{ .Values.Namespace }}
spec:
  maxUnavailable: {{ .Values.maxUnavailable }}
  selector:
    matchLabels:
      app: "{{ template "myelasticsearch.uname" . }}"
{{- end }}
