stages:
  - build
  - deploy

variables:
  DOCKER_IMAGE_NAME: registry.example.com/your-project/your-app-name:latest

build:
  stage: build
  image: docker:latest
  script:
    - docker build -t $DOCKER_IMAGE_NAME .
    - docker push $DOCKER_IMAGE_NAME
  only:
    - master

deploy:
  stage: deploy
  image: alpine
  script:
    - apk add --no-cache openssh-client
    - mkdir -p ~/.ssh
    - echo "$DEPLOYMENT_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan 192.168.10.72 >> ~/.ssh/known_hosts
    - scp -r ./* rtambakhe@192.168.10.72:/path/to/deployment/directory/
    - ssh rtambakhe@192.168.10.72 "docker-compose -f /path/to/deployment/directory/docker-compose.yml up -d"
  only:
    - master
