apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.clusterRoleBinding.name }}
roleRef:
  apiGroup: {{ .Values.clusterRoleBinding.roleRefApiGroup }}
  kind: {{ .Values.clusterRoleBinding.roleRefKind }}
  name: {{ .Values.clusterRoleBinding.roleRefName }}
subjects:
  - kind: {{ .Values.clusterRoleBinding.subjectsKind }}
    name: {{ .Values.clusterRoleBinding.subjectsName }}
    namespace: {{ .Values.clusterRoleBinding.subjectsNamespace }}
