apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.clusterRole.name }}
rules:
  - apiGroups:
      - {{ .Values.clusterRole.apiGroups }}
    resources:
      - {{ .Values.clusterRole.resources }}
    verbs:
      - get
      - watch
      - list
