controller:
  kind: DaemonSet
  admissionWebhooks:
    enabled: false
  metrics:
    enabled: true
  service:
    type: ClusterIP
  podAnnotations:
    elasticsearch.io/path: /metrics
    elasticsearch.io/port: "10254"
    elasticsearch.io/scheme: http
    elasticsearch.io/scrape: "true"
